### PR TITLE
Update to Alpine 3.14

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Ooop, https://github.com/docker-library/ghost/pull/258 -- @acburdine any idea if that's still relevant or if this is fine to go ahead?

(We have to do something because `node`'s `alpine3.12` variant is gone now. :sweat_smile:)

**Comment by acburdine** [comment]
@tianon I'll build this PR and test the fix later today 👍🏻

**Comment by acburdine** [comment]
@tianon apologies for the delay in testing (been a busy first week back) - will do my best to get to this today

**Comment by acburdine** [comment]
still running tests, but after looking at the PR again I think things _should_ be fine because we reverted the change in #258 in https://github.com/docker-library/ghost/pull/263

**Review by acburdine — APPROVED** [review]

**Comment by tianon** [comment]
Nice, thanks for testing! :smile: :+1:

**Pull request merged**
