### PR TITLE
Adding an easy unit-test script

### PR DESCRIPTION
**Pull request by pascalandy**
I am at a point where I create unit tests for most of the containers I work with. (My builds are scripted and it calls the unit-test.sh at the end once it’s built.)

I think it would be great if you guys (Docker maintainers) would help to the community to define what should be the unit test for a particular application.

Here is my take for Ghost :)  
  
Cheers!
https://twitter.com/_pascalandy

### CODE REVIEW

**Comment by tianon** [comment]
Interesting!  As you can see from the Travis log on this PR (https://travis-ci.org/docker-library/ghost/builds/196629970#L9180-L9188), we've got a set of tests over in https://github.com/docker-library/official-images/tree/master/test, although we don't have any Ghost-specific tests yet. :smile:

**Comment by pascalandy** [comment]
I'm not familiar about general CI unit tests.

Here I'm more interested to get the best Unit Test for application X. Ghost in this case.

My minding here is to let the community run a script (i.e. unit-test.sh) after we build our image. In this PR I included 4 checkpoints.

I'm looking for the Ghost 'experts' to help me getting this right :)

Cheers!

**Comment by kevinansfield** [comment]
Hey @pascalandy, it sounds like you want to test the container setup rather than Ghost itself, eg. does the ghost process start and shut down successfully?

I'm not sure running Ghost's existing test suite would help too much - as unit tests they are designed to test the code itself rather than the environment. Please correct me if I'm mistaken 😄

**Comment by pascalandy** [comment]
You are correct @kevinansfield. In the container context, I want to test the container setup and ensure Ghost is perfectly installed.

I guess are you right that existing test suite is probably not gonna work.
> I'm not sure running Ghost's existing test suite would help too much - as unit tests they are designed to test the code itself rather than the environment

**Comment by ErisDS** [comment]
Whilst I wouldn't have a clue how, my suggestions would be to check:

- that your-url-here/ghost/ loads
- that your-url-here/ghost/setup/ redirects to signin (means the blog has an owner account configured)
- that email is configured (hard one - there is an api endpoint but that's currently secured by user-auth).

Long term, this is the kind of thing that the [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI) tool might have baked in. It already has a health check to test that your environment is in a state where Ghost can be installed.

**Comment by pascalandy** [comment]
Thank you Hannah @ErisDS for your input. Yes, I do these tests when I deploy a new blog but this is off topic. The challenge here:

1. Does not work. When you build the image and test it, this image is not deployed anywhere. The URL is usually not hard coded in the config.js but passed as an argument when you `docker run ...`
> that your-url-here/ghost/ loads
2.  Does not work. See point above
> that your-url-here/ghost/setup/ redirects to signin (means the blog has an owner account configured)
3.  Does not work. Same story, there is no email hard coded in the image.
> that email is configured (hard one - there is an api endpoint but that's currently secured by user-auth).

If you look at lines 10-11-12 of [my PR](https://github.com/docker-library/ghost/pull/59/files#diff-f59f9d31b45d26d4e18d74c6e8faf266R10), these are the CMD that makes a valid unit test for my docker images:

- A) "node --version"
- B) "npm show"
- C) "ls -AlhF /usr/src/ghost/content/themes"

Context about **C)**: I copy few themes along Casper so I can see them listed. I have a based image with my "stable themes" and a dev image for my "edge themes"

**Any other suggestions** about CMDs that would validate Ghost is perfectly installed?

Cheers!

**Comment by pascalandy** [comment]
I think we could investigate the Ghost CLI and see if there is such a fonction in it.

**Comment by pascalandy** [comment]
Let's continue the conversation here: https://github.com/docker-library/ghost/issues/90

**Pull request closed without merging**
