### PR TITLE
Remove unsupported versions, https://dev.ghost.org/lts/

### PR DESCRIPTION
**Pull request by yosifkit**
https://dev.ghost.org/lts/

### CODE REVIEW

**Comment by acburdine** [comment]
The LTS post says that maintenance releases will be run up until March 2017 - so I don't see exactly why we should remove the 0.11.x line? There could still be maintenance/security fixes in between now and March.

**Comment by tianon** [comment]
That's March of this year, as in, five months ago, right? :smile:

**Comment by tianon** [comment]
Maybe that post is outdated, and the target EOL date has since changed? (0.11.11 was something like 16 days ago, after all)

**Comment by tianon** [comment]
Aha! From https://dev.ghost.org/ghost-1-0-0/:

> Because the upgrade process is more complex this time around, we've marked Ghost 0.11 as a Long Term Support (LTS) release. We will continue to provide maintenance and security updates for Ghost 0.11 for the next 6 months.

**Comment by tianon** [comment]
So looks like 0.x gets to stick around until ~Jan 2018.

**Comment by acburdine** [comment]
Oops lol - yeah sorry, completely misread the post 😆

**Comment by yosifkit** [comment]
Swapped to keep `0.x` series.

**Pull request merged**
