### PR TITLE
Update to 4.44.0

### PR DESCRIPTION
**Pull request by acburdine**
couldn't push to the branch for #297, so created a separate PR 😅 

see https://github.com/docker-library/ghost/pull/297#issuecomment-1101921390 for an explanation of the fix

### CODE REVIEW

**Review by yosifkit — APPROVED** [review]

**Comment by yosifkit** [comment]
This won't bring back build failures in non-amd64 architectures (https://github.com/docker-library/ghost/pull/259), will it?

**Comment by acburdine** [comment]
@yosifkit it might, I didn't test for that yesterday 😞 I can test for that later tonight though.

If it _does_ break the build for those architectures, would it make sense to ship this to fix the build for alpine and debian/amd64 architectures?

**Comment by yosifkit** [comment]
Good news is that this builds and a plain `docker run` works on `arm64v8`.

**Comment by yosifkit** [comment]
Good news is that this builds and a plain `docker run` works on `arm64v8`.

**Comment by acburdine** [comment]
> Good news is that this builds and a plain docker run works on arm64v8.

yay! Should I go ahead and merge this then?

**Comment by yosifkit** [comment]
Sure, we can always add more if we have issues on the more esoteric architectures.

**Comment by acburdine** [comment]
created the official-images PR here: https://github.com/docker-library/official-images/pull/12262

**Pull request merged**
