### PR TITLE
feat: add v4 dockerfiles

### PR DESCRIPTION
**Pull request by acburdine**
copies of the v3 images, with a couple of links & the version env vars updated.

### CODE REVIEW

**Comment by acburdine** [comment]
looks like this _might_ be an issue with the ghost npm version, gonna double check locally

**Comment by yosifkit** [comment]
:+1: initial diff look great:

```diff
$ git diff --no-index 3/ 4/
diff --git a/3/alpine/Dockerfile b/4/alpine/Dockerfile
index 3893a2e..32764f4 100644
--- a/3/alpine/Dockerfile
+++ b/4/alpine/Dockerfile
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/faq/node-versions/
 # https://github.com/nodejs/LTS
-# https://github.com/TryGhost/Ghost/blob/3.3.0/package.json#L38
+# https://github.com/TryGhost/Ghost/blob/v4.0.0/package.json#L38
 FROM node:12-alpine3.12
 
 # grab su-exec for easy step-down from root
@@ -20,7 +20,7 @@ RUN set -eux; \
 ENV GHOST_INSTALL /var/lib/ghost
diff --git a/3/alpine/Dockerfile b/4/alpine/Dockerfile
index 3893a2e..32764f4 100644
--- a/3/alpine/Dockerfile
+++ b/4/alpine/Dockerfile
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/faq/node-versions/
 # https://github.com/nodejs/LTS
-# https://github.com/TryGhost/Ghost/blob/3.3.0/package.json#L38
+# https://github.com/TryGhost/Ghost/blob/v4.0.0/package.json#L38
 FROM node:12-alpine3.12
 
 # grab su-exec for easy step-down from root
@@ -20,7 +20,7 @@ RUN set -eux; \
 ENV GHOST_INSTALL /var/lib/ghost
 ENV GHOST_CONTENT /var/lib/ghost/content
 
-ENV GHOST_VERSION 3.42.2
+ENV GHOST_VERSION 4.0.0
 
 RUN set -eux; \
        mkdir -p "$GHOST_INSTALL"; \
diff --git a/3/debian/Dockerfile b/4/debian/Dockerfile
index 810ce7e..18137e7 100644
--- a/3/debian/Dockerfile
+++ b/4/debian/Dockerfile
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/faq/node-versions/
 # https://github.com/nodejs/LTS
:...skipping...
diff --git a/3/alpine/Dockerfile b/4/alpine/Dockerfile
index 3893a2e..32764f4 100644
--- a/3/alpine/Dockerfile
+++ b/4/alpine/Dockerfile
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/faq/node-versions/
 # https://github.com/nodejs/LTS
-# https://github.com/TryGhost/Ghost/blob/3.3.0/package.json#L38
+# https://github.com/TryGhost/Ghost/blob/v4.0.0/package.json#L38
 FROM node:12-alpine3.12
 
 # grab su-exec for easy step-down from root
@@ -20,7 +20,7 @@ RUN set -eux; \
 ENV GHOST_INSTALL /var/lib/ghost
 ENV GHOST_CONTENT /var/lib/ghost/content
 
-ENV GHOST_VERSION 3.42.2
+ENV GHOST_VERSION 4.0.0
 
 RUN set -eux; \
        mkdir -p "$GHOST_INSTALL"; \
diff --git a/3/debian/Dockerfile b/4/debian/Dockerfile
index 810ce7e..18137e7 100644
--- a/3/debian/Dockerfile
+++ b/4/debian/Dockerfile
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/faq/node-versions/
 # https://github.com/nodejs/LTS
-# https://github.com/TryGhost/Ghost/blob/3.3.0/package.json#L38
+# https://github.com/TryGhost/Ghost/blob/v4.0.0/package.json#L38
 FROM node:12-buster-slim
 
 # grab gosu for easy step-down from root
@@ -44,7 +44,7 @@ RUN set -eux; \
 ENV GHOST_INSTALL /var/lib/ghost
 ENV GHOST_CONTENT /var/lib/ghost/content
 
-ENV GHOST_VERSION 3.42.2
+ENV GHOST_VERSION 4.0.0
 
 RUN set -eux; \
        mkdir -p "$GHOST_INSTALL"; \
~
```

**Comment by acburdine** [comment]
confirmed the test failures are a bug in Ghost, specifically with the release process on npm. Working on getting it fixed 🔨

**Comment by yosifkit** [comment]
Since this is a release, you'll also want to update `latest`:
https://github.com/docker-library/ghost/blob/94891835578da2a7c4c4d5a1661c55d98b865801/generate-stackbrew-library.sh#L5

**Comment by acburdine** [comment]
@yosifkit this will also require https://github.com/docker-library/official-images/pull/9796 due to some changes in Ghost's boot stack that currently break the tests 😬

**Review by GitMajkHub — APPROVED** [review]

**Comment by acburdine** [comment]
had to bump to v4.0.1 because of a bug, but should be good now 😄

**Pull request merged**
