### PR TITLE
Update Ghost 4 to Node 14

### LINKED ISSUE #253: Using Node:12 versus Node:14
Hello Austin @acburdine 

Not sure if I should ask here or on the Ghost forum. As I prefer Github, I'll do it here :-p

It's regarding the Node's version. On https://ghost.org/docs/faq/node-versions/ the recommended version is **v14**.
But in this Dockerfile (alpine) we stick to `node:12-alpine3.12`

I tried to bump to `node:14-alpine3.13` but the CI crash on this line: https://github.com/docker-library/ghost/blob/master/4/alpine/Dockerfile#L51 (My CI [logs](https://github.com/firepress-org/ghostfire/runs/2231455538?check_suite_focus=true)) 

Just want to make sure that everyone is aware about this delta. I think we should follow the recommend node version. I didn't investigate the reason yet.

Cheers!
P

### PR DESCRIPTION
**Pull request by tianon**
Closes #253

### CODE REVIEW

**Comment by tianon** [comment]
@pascalandy not sure why your CI failed, but this appears to be fine? :sweat_smile:

@acburdine do you think this makes sense?  Should we also update any of the older Ghost releases?

**Review by acburdine — APPROVED** [review]

**Comment by acburdine** [comment]
Apologies for the delay @tianon - was on vacation last week 😅 

Looks good to me 👍🏻

**Comment by tianon** [comment]
Totally fair!  I'm jealous 😂

Do you think we should do this to any of the older versions, or stick to just 4.x+?

**Comment by acburdine** [comment]
> Do you think we should do this to any of the older versions, or stick to just 4.x+?

Probably just stick to 4.x for now, v2 doesn't even have support for v14 as far as I know

**Pull request merged**
