### PR TITLE
Adjust knex-migrator to be in the PATH directly instead of symlinking

### LINKED ISSUE #103: ENH: Simplify the way knex is added to the path
Instead of linking the knex migrator file into the bin folder 
```bash
        for f in "$GHOST_INSTALL/current/node_modules/.bin/knex-migrator"*; do \
		[ -x "$f" ]; \
		ln -svf "$f" /usr/local/bin/; \
	done
```
I think it is easier to add the knex bin folder to the user path:
`ENV PATH="${GHOST_INSTALL}/current/node_modules/knex-migrator/bin:${PATH}"`

It is working and tested [here](https://github.com/mmornati/docker-ghostblog/blob/master/Dockerfile)

### PR DESCRIPTION
**Pull request by tianon**
Closes #103

Thanks @mmornati

### CODE REVIEW

**Comment by mmornati** [comment]
Welcome ;)
It is my Docker-inspiration... so thank you too.

**Comment by SISheogorath** [comment]
When you use `npm` to execute it, there is no need to symlink or path it.

**Comment by mmornati** [comment]
Yes. But there is no need to install it via npm cause it is inside the
Ghost dependencies.
I think a good target is to keep the the images smaller.
The knex is taking lot of space... So why we need to have it 2 times?

**Comment by SISheogorath** [comment]
I'm not saying installing it, I say running it. Using `npm run`. Docs go here: https://docs.npmjs.com/cli/run-script

**Comment by tianon** [comment]
@SISheogorath that'll work for our own usage, but not for folks who've extended this image and want to use `knex-migrator*` (which have been in `PATH` until now in every incarnation of the `ghost:1` image)

If the `knex-migrator*` tools were something only our scripts would ever need to execute, I'd be inclined to agree that using `npm run ...` is simpler. :heart:

**Pull request merged**
