### PR TITLE
Run as non-root by default

### PR DESCRIPTION
**Pull request by tianon**
@md5 :heart: (https://github.com/docker-library/official-images/pull/505#issuecomment-75314321)

I'd much rather be non-root from the start than try to backpedal later.

### CODE REVIEW

**Comment by tianon** [comment]
`npm start` is the way upstream explains you should run, but I also see mention of `node index.js` being acceptable -- not sure which one we should standardize on :confused:

**Comment by md5** [comment]
I would recommend using `npm start`. If they later decide to update the start script to something other than `node index`, they'll do it here: https://github.com/TryGhost/Ghost/blob/2a91a1071e4d4d7a5a4bfea971a77b6eed6a9349/package.json#L26

**Comment by yosifkit** [comment]
LGTM

**Comment by md5** [comment]
LGTM too.

**Comment by tianon** [comment]
:heart:

**Pull request merged**
