### PR TITLE
Refactor 5.x installation to allow for building where necessary

### LINKED ISSUE #307: ghost 5 alpine image won’t build
Hi seeing this error:

`=> ERROR [internal] load metadata for docker.io/library/ghost:5-alpine 
------
 > [internal] load metadata for docker.io/library/ghost:5-alpine:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = no match for platform in manifest sha256:dc6ce9363c6dcd0db732f130d7dc353175f63013fcfa0fe6458ee6fabd564c73: not found`

### PR DESCRIPTION
**Pull request by tianon**
Closes #307

I don't love how complex this has become, but I do like that it's a lot more resilient? :grimacing: :see_no_evil:

I've tested this successfully on at least `arm64v8`, `s390x`, and `ppc64le` (the latter of which don't get `sharp` successfully because they don't have pre-built or new enough `libvips` :disappointed:).

### CODE REVIEW

**Review by yosifkit — APPROVED** [review]

**Comment by unverbraucht** [comment]
Checked this the other day on a M1 (arm64) macbook, builds and runs great. Currently building on a armv7 Raspi, also seems to be building fine.

**Comment by XChikuX** [comment]
@tianon Hey any update on v7 ?

I don't get sharp installed on my end when attempting this.

**Comment by pascalandy** [comment]
To fix this, use your own multi stage build. Install sharp normally (debien per example) than copy in within your image v7.

**Comment by XChikuX** [comment]
@pascalandy Respectfully, that's not a fix. It's a workaround.

**Comment by yosifkit** [comment]
It looks like `vips-dev` on Alpine 3.17 (current base) is new enough for sharp now: https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=v3.17&repo=&arch=&maintainer= (I'll make a PR).

When we move to Debian Bookworm, it will also have new enough "libvips": https://packages.debian.org/bookworm/libvips-dev.

**Pull request merged**
