### PR TITLE
Updates for Ghost 1.0

### PR DESCRIPTION
**Pull request by acburdine**
This PR will do a couple of things:

- [x] Update the base node version of Ghost 0.11.x to 6 as per the [supported node version docs](https://docs.ghost.org/v0.11.9/docs/supported-node-versions)
- [x] Add 1.0 docker configs
- [x] update the stackbrew file (may need some help w/that)

### CODE REVIEW

**Comment by sharkoz** [comment]
I just submitted a PR for the failed test here : https://github.com/docker-library/official-images/pull/3254

It comes from the fact that in v0.*, /ghost/ redirects through HTTP to setup, but now in v1.*, the check is done via Javascript through an API (`/ghost/api/v0.1/authentication/setup/`)

When my PR is merged, the tests should pass.

**Comment by yosifkit** [comment]
Added a commit to update `generate-stackbrew-library.sh` as well as catch when users mount a host folder to `GHOST_CONTENT` and sped up `chown`s by just installing as the correct user.

**Comment by rachelbasse** [comment]
You might also want to add a volume for the themes (/var/lib/ghost/versions). I didn't want to lose the ones I had installed.

**Comment by yosifkit** [comment]
@rachelbasse, there is already a volume on `GHOST_CONTENT` (`/var/lib/ghost/content`) and, as far as I understand, themes will be installed in the themes directory inside of content.

**Comment by rachelbasse** [comment]
@yosifkit, perhaps you should test your understanding against an actual running example? In my actual running container, `/var/lib/ghost/content/themes` contains **only** `casper`, but '/var/lib/ghost/versions/1.1.0/content/themes` contains `casper` **and** the theme that I installed via the admin UI---which I lost when I rebuilt the container. Thanks.

**Comment by yosifkit** [comment]
Did you use the most recent version here? With the explicitly set `paths.contentPath "$GHOST_CONTENT"` it stores themes in the correct spot. I just ran the image and uploaded a theme zip and it is working as it should:
```console
root@4e0d36ed0a33:/var/lib/ghost# ls -l content/themes/
total 4
drwxr-xr-x 4 node node 4096 Aug  1 20:18 affinity.1.4.0
lrwxrwxrwx 1 node node   44 Aug  1 18:07 casper -> /var/lib/ghost/current/content/themes/casper
```

With a named volume I can delete the container and start a new one up again:
```console
$ docker run -d -v ghostContent:/var/lib/ghost/content/ --name ghosty ghost:1.0
$ # create user, install a theme, etc
$ docker stop ghosty
$ docker rm ghosty
$ docker run -d -v ghostContent:/var/lib/ghost/content/ --name ghosty ghost:1.0
$ # theme is on the "new" blog; user still works

**Comment by acburdine** [comment]
@yosifkit the changes look good - thanks for helping with them 😄

**Comment by yosifkit** [comment]
I will merge this and then get the PR to official-images up, but it looks like there is already a ghost 1.2.  Does 1.2 replace 1.0?  I'll still get the 1.0 pushed to the Docker Hub asap and we can add/bump 1.2 in parallel.

**Comment by rachelbasse** [comment]
@yosifkit Nope, was popping in quickly to suggest a fix to the original without looking at your changes. No comments suggested anyone was aware of this problem. If setting contentPath fixes it, that seems like a better solution.

**Comment by yosifkit** [comment]
Thanks @rachelbasse, we do want to make sure that defined volumes are actually useful. Thanks for checking!

**Comment by yosifkit** [comment]
@acburdinem, I was going to add the three new versions (1.1, 1.2, 1.3) and it looks like ghost-cli needs a bump for 1.3.  Would it hurt to have Ghost-CLI 1.0.3 for all 4 versions of ghost? I could add auto-updating the cli version to `update.sh` or we can leave it to be a manual process for now.

One other question is how many versions do we keep once we get these intermediary versions added to Docker Hub?

**Comment by yosifkit** [comment]
See https://github.com/docker-library/ghost/pull/68 for the new versions.

**Comment by acburdine** [comment]
@yosifkit so Ghost-CLI is designed to be compatible with any version of Ghost >= 1.0.0 - so it's fine to update the Ghost-CLI version to 1.0.3 for the docker image 😄

**Pull request merged**
