### PR TITLE
Adding the actual node version in the comment

### PR DESCRIPTION
**Pull request by pascalandy**
Useful when you have to open a ticket at https://github.com/TryGhost/Ghost/issues

### CODE REVIEW

**Comment by pascalandy** [comment]
Found using `node --version`

**Comment by tianon** [comment]
This is going to vary as the `node:4-slim` tag is updated -- if it's important for users to know how to get this sort of information, I'd rather we document it in the image description (either `docker run --rm <image> node --version` or `docker exec <container> node --version`).

**Comment by pascalandy** [comment]
Agreed. Here is my PR - https://github.com/docker-library/docs/pull/663

**Comment by tianon** [comment]
Thanks!  We'll continue over there.

**Pull request closed without merging**
