### PR TITLE
Make container better behaved by adding dumb-init

### PR DESCRIPTION
**Pull request by stewartml**
Add [dumb-init](https://github.com/Yelp/dumb-init) to fix issues where container refuses to die.

### CODE REVIEW

**Comment by yosifkit** [comment]
Oh, I had assumed that they actually listened for signals since they have the `Ctrl+C to shut down` in the logs. It seems that npm doesn't forward signals to the node app so signals only work when npm is out of the way.  The simpler fix is to just change `CMD` to `["node", "index"]`, which is recommended in the node-docker [best practices](https://github.com/nodejs/docker-node/blob/bb5b057d4edd25fb26ba6eefc9d33e778102297d/docs/BestPractices.md#cmd).

```console
$ signals=( INT TERM KILL )
$ docker run -d --name ghost ghost node index && sleep 5 && for sig in "${signals[@]}"; do (sleep 1; set -x; docker kill -s $sig ghost > /dev/null; docker ps -l); done; docker rm ghost
aa0f8d94421c303e0fca45342256c33ae8004e07476d0f54378b4965609bef63
+ docker kill -s INT ghost
+ docker ps -l
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
aa0f8d94421c        ghost               "/entrypoint.sh node "   6 seconds ago       Up 6 seconds        2368/tcp            ghost
+ docker kill -s TERM ghost
Error response from daemon: Cannot kill container ghost: notrunning: Container aa0f8d94421c303e0fca45342256c33ae8004e07476d0f54378b4965609bef63 is not running
Error: failed to kill containers: [ghost]
+ docker ps -l
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
aa0f8d94421c        ghost               "/entrypoint.sh node "   7 seconds ago       Exited (0) 1 seconds ago                       ghost
+ docker kill -s KILL ghost
Error response from daemon: Cannot kill container ghost: notrunning: Container aa0f8d94421c303e0fca45342256c33ae8004e07476d0f54378b4965609bef63 is not running
Error: failed to kill containers: [ghost]
+ docker ps -l
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
aa0f8d94421c        ghost               "/entrypoint.sh node "   8 seconds ago       Exited (0) 2 seconds ago                       ghost
ghost
```

**Comment by yosifkit** [comment]
On the other hand, does using `node start` cause the unreaped zombie children problem?

**Comment by stewartml** [comment]
Sorry for the delay, was on holiday!  AFAIK, it's not specifically that npm isn't forwarding the signals, it's that the signals are [not forwarded normally](https://github.com/Yelp/dumb-init#why-you-need-an-init-system) in general for PID 1

**Comment by tianon** [comment]
Is there a simple way to reproduce the issue (such as `docker kill -s TERM some-ghost` not killing the container)?

**Comment by tianon** [comment]
Definitely liking @yosifkit's / Node.js maintainers' recommendation:
```console
$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
tianon              24095               24078               10                  13:40               pts/13              00:00:01            npm
tianon              24191               24095               0                   13:40               pts/13              00:00:00            sh -c node index
tianon              24192               24191               40                  13:40               pts/13              00:00:02            node index
```

Then we'd only have the single `node index` process running and the image is simplified. :+1:

**Comment by tianon** [comment]
This is fixed as of 1.x! (since we use `node current/index.js` to launch Ghost directly, and `npm` is no longer involved :+1:)

**Pull request closed without merging**
